language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7"
  - "nightly" 
# command to install dependencies
install:
  - pip install -r requirements.py
# command to run tests
script: 
  - py.test
after_script:
  - bash .travis/push-docs.sh
